//All AVR ATmega 16 Registers 


#ifndef Regs
#define Regs

#include "std_types.h"
#define PORTA *((volatile PU8)(0x3B))
#define PORTB *((volatile PU8)(0x38))
#define PORTC *((volatile PU8)(0x35))
#define PORTD *((volatile PU8)(0x32))
#define PINA *((volatile PU8)(0x39))
#define PINB *((volatile PU8)(0x36))
#define PINC *((volatile PU8)(0x33))
#define PIND *((volatile PU8)(0x30))
#define DDRD *((volatile PU8)(0x31))
#define DDRC *((volatile PU8)(0x34))
#define DDRB *((volatile PU8)(0x37))
#define DDRA *((volatile PU8)(0x3A))
#define SREG *((volatile PU8)(0x5F))
#define SPH *((volatile PU8)(0x5E))
#define SPL *((volatile PU8)(0x5D))
#define OCR0 *((volatile PU8)(0x5C))
#define GICR *((volatile PU8)(0x5B))
#define GIFR *((volatile PU8)(0x5A))
#define TIMSK *((volatile PU8)(0x59))
#define TIFR *((volatile PU8)(0x58))
#define SPMCR *((volatile PU8)(0x57))
#define TWCR *((volatile PU8)(0x56))
#define MCUCR *((volatile PU8)(0x55))
#define MCUCSR *((volatile PU8)(0x54))
#define TCCR0 *((volatile PU8)(0x53))
#define TCNT0 *((volatile PU8)(0x52))
#define OSCCAL *((volatile PU8)(0x51))
#define OCDR *((volatile PU8)(0x51))
#define SFIOR *((volatile PU8)(0x50))
#define TCCR1A *((volatile PU8)(0x4F))
#define TCCR1B *((volatile PU8)(0x4E))
#define TCNT1H *((volatile PU8)(0x4D))
#define TCNT1L *((volatile PU8)(0x4C))
#define OCR1AH *((volatile PU8)(0x4B))
#define OCR1AL *((volatile PU8)(0x4A))
#define OCR1BH *((volatile PU8)(0x49))
#define OCR1BL *((volatile PU8)(0x48))
#define ICR1H *((volatile PU8)(0x47))
#define ICR1L *((volatile PU8)(0x46))
#define TCCR2 *((volatile PU8)(0x45))
#define TCNT2 *((volatile PU8)(0x44))
#define OCR2 *((volatile PU8)(0x43))
#define ASSR *((volatile PU8)(0x42))
#define WDTCR *((volatile PU8)(0x41))
#define UBRRH *((volatile PU8)(0x40))
#define UCSRC *((volatile PU8)(0x40))
#define EEARH *((volatile PU8)(0x3F))
#define EEARL *((volatile PU8)(0x3E))
#define EEDR *((volatile PU8)(0x3D))
#define EECR *((volatile PU8)(0x3C))
#define SPDR *((volatile PU8)(0x2F))
#define SPSR *((volatile PU8)(0x2E))
#define SPCR *((volatile PU8)(0x2D))
#define UDR *((volatile PU8)(0x2C))
#define UCSRA *((volatile PU8)(0x2B))
#define UCSRB *((volatile PU8)(0x2A))
#define UBRRL *((volatile PU8)(0x29))
#define ACSR *((volatile PU8)(0x28))
#define ADMUX *((volatile PU8)(0x27))
#define ADCSRA *((volatile PU8)(0x26))
#define ADCH *((volatile PU8)(0x25))
#define ADCL *((volatile PU8)(0x24))
#define TWDR *((volatile PU8)(0x23))
#define TWAR *((volatile PU8)(0x22))
#define TWSR *((volatile PU8)(0x21))
#define TWBR *((volatile PU8)(0x20))

#endif
